/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FRONTEND;

import BACKEND.Administrador;
import BACKEND.CentroVacinacao;
import BACKEND.Gestor;
import BACKEND.Sistema;
import BACKEND.Utente;
import Serializacao.Serializacao;
import javax.swing.JOptionPane;

/**
 *
 * @author guilh
 */
public class JanelaPrincipal extends javax.swing.JFrame {

    /**
     *
     */
    private Sistema sistema;

    /**
     *
     */
    private Serializacao bd;

    /**
     *
     * @param sistema
     * @param bd
     */
    public JanelaPrincipal(Sistema sistema, Serializacao bd) {
        initComponents();

        Lgestor.setVisible(false);
        Ladmin.setVisible(false);
        Lutente.setVisible(false);

        this.sistema = sistema;
        this.bd = bd;
        this.setTitle("MENU INICIAL");
        this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        this.setResizable(false);
        this.setLocationRelativeTo(null);

        menuAdmin.setVisible(sistema.getUtilizadorligado() instanceof Administrador);
        menuGestor.setVisible(sistema.getUtilizadorligado() instanceof Gestor);
        menuUtente.setVisible(sistema.getUtilizadorligado() instanceof Utente);
        UtiLigado.setText("Utilizador Ligado: " + sistema.getUtilizadorligado().getUsername());
        preencherImagem();

        if (sistema.getUtilizadorligado() instanceof Utente) {
            menuUtente();
        }

    }

    /**
     *
     */
    private void centroVacinacao() {
        JanelaConsultarCentroDeVacinacao cv = new JanelaConsultarCentroDeVacinacao(sistema, (Utente) sistema.getUtilizadorligado(), bd);
        cv.setVisible(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu9 = new javax.swing.JMenu();
        jMenu10 = new javax.swing.JMenu();
        UtiLigado = new javax.swing.JLabel();
        Lutente = new javax.swing.JLabel();
        Ladmin = new javax.swing.JLabel();
        Lgestor = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        menuAdmin = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem17 = new javax.swing.JMenuItem();
        menuGestor = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        menuUtente = new javax.swing.JMenu();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        jMenu7.setText("jMenu7");

        jMenuItem9.setText("jMenuItem9");

        jMenu9.setText("File");
        jMenuBar3.add(jMenu9);

        jMenu10.setText("Edit");
        jMenuBar3.add(jMenu10);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        UtiLigado.setForeground(new java.awt.Color(0, 0, 0));
        UtiLigado.setText("Utilizador ligado: ");
        getContentPane().add(UtiLigado, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, 230, 28));

        Lutente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons/utenteligado.png"))); // NOI18N
        Lutente.setText("jLabel2");
        getContentPane().add(Lutente, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, 5, 460, 330));

        Ladmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons/adminligado.png"))); // NOI18N
        Ladmin.setText("Ladmin");
        getContentPane().add(Ladmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 340));

        Lgestor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons/1.png"))); // NOI18N
        getContentPane().add(Lgestor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 340));

        jMenu1.setText("Opções");

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons/disquete.png"))); // NOI18N
        jMenuItem1.setText("Guardar Alterações");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons/sair.png"))); // NOI18N
        jMenuItem14.setText("Sair");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem14);

        jMenuBar1.add(jMenu1);

        menuAdmin.setText("Menu");

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons/do-utilizador (3).png"))); // NOI18N
        jMenuItem2.setText("Gestores");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        menuAdmin.add(jMenuItem2);

        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons/centro-medico (1).png"))); // NOI18N
        jMenuItem5.setText("Centros de Vacinação");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        menuAdmin.add(jMenuItem5);

        jMenuItem11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons/vacina.png"))); // NOI18N
        jMenuItem11.setText("Vacinas");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        menuAdmin.add(jMenuItem11);

        jMenuItem17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons/grafico.png"))); // NOI18N
        jMenuItem17.setText("Estatísticas Vacinação");
        jMenuItem17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem17ActionPerformed(evt);
            }
        });
        menuAdmin.add(jMenuItem17);

        jMenuBar1.add(menuAdmin);

        menuGestor.setText("Menu");

        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons/centro-medico (1).png"))); // NOI18N
        jMenuItem3.setText("Centro de Vacinação");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        menuGestor.add(jMenuItem3);

        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons/agenda.png"))); // NOI18N
        jMenuItem6.setText("Marcações");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        menuGestor.add(jMenuItem6);

        jMenuItem7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons/vacina.png"))); // NOI18N
        jMenuItem7.setText("Vacinas");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        menuGestor.add(jMenuItem7);

        jMenuItem8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons/cara.png"))); // NOI18N
        jMenuItem8.setText("Utentes");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        menuGestor.add(jMenuItem8);

        jMenuItem10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons/vacinacao.png"))); // NOI18N
        jMenuItem10.setText("Vacinação");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        menuGestor.add(jMenuItem10);

        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons/computador.png"))); // NOI18N
        jMenuItem4.setText("Faltas à Vacinação");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        menuGestor.add(jMenuItem4);

        jMenuItem16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons/grafico.png"))); // NOI18N
        jMenuItem16.setText("Estatística da Vacinação");
        jMenuItem16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem16ActionPerformed(evt);
            }
        });
        menuGestor.add(jMenuItem16);

        jMenuBar1.add(menuGestor);

        menuUtente.setText("Menu");

        jMenuItem12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons/agenda.png"))); // NOI18N
        jMenuItem12.setText("Fazer marcação");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        menuUtente.add(jMenuItem12);

        jMenuItem13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons/vacinacao (1).png"))); // NOI18N
        jMenuItem13.setText("Consultar Marcação");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        menuUtente.add(jMenuItem13);

        jMenuItem15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons/ponto-de-informacao.png"))); // NOI18N
        jMenuItem15.setText("Dados Utente");
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem15ActionPerformed(evt);
            }
        });
        menuUtente.add(jMenuItem15);

        jMenuBar1.add(menuUtente);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        bd.guardar(sistema);
        JOptionPane.showConfirmDialog(null, "Deseja guardar a informação do sistema?", "Guardar", JOptionPane.YES_NO_OPTION);

    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        JanelaListarGestores j = new JanelaListarGestores(sistema, bd);
        j.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        Gestor g = (Gestor) sistema.getUtilizadorligado();
        try {
            CentroVacinacao cv = sistema.getCentrosVacinacoes().getCentroVacinacaoPorGestor(g);
            JanelaMarcacoesGestor j = new JanelaMarcacoesGestor(sistema, bd, cv);
            j.setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "O Gestor não tem nenhum Centro associado", "ERRO", HEIGHT);
        }

    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        Utente u = (Utente) sistema.getUtilizadorligado();

        if (u.getCentrovacinacao() == null) {
            JOptionPane.showMessageDialog(rootPane, "O Utente ainda não tem centro de vacinação associado", "ERRO", HEIGHT);
        } else {

            JanelaFazerPrimeiraMarcacao j = new JanelaFazerPrimeiraMarcacao(sistema, bd);
            j.setVisible(true);
            jMenuItem12.setVisible(false);

        }

    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        JanelaConsultarMarcacoes j = new JanelaConsultarMarcacoes(sistema, bd);
        j.setVisible(true);
        menuUtente();
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
        bd.guardar(sistema);
        if (JOptionPane.showConfirmDialog(null, "Deseja encerrar o sistema?", "SAIR", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            bd.guardar(sistema);
            sistema.terminar();

        }
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        JanelaListarCentroVacinacoes j = new JanelaListarCentroVacinacoes(sistema, bd);
        j.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15ActionPerformed
        JanelaDadosUtente j = new JanelaDadosUtente(sistema, (Utente) sistema.getUtilizadorligado(), bd);
        j.setVisible(true);
        menuUtente();
    }//GEN-LAST:event_jMenuItem15ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        sistema.terminar();
    }//GEN-LAST:event_formWindowClosing

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        JanelaAlocarVacinas j = new JanelaAlocarVacinas(sistema, bd);
        j.setVisible(true);
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        Gestor g = (Gestor) sistema.getUtilizadorligado();
        try {
            CentroVacinacao cv = sistema.getCentrosVacinacoes().getCentroVacinacaoPorGestor(g);
            JanelaCentroVacinacaoGestor j = new JanelaCentroVacinacaoGestor(sistema, bd, cv);
            j.setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "O Gestor não tem nenhum Centro associado", "ERRO", HEIGHT);
        }

    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        Gestor gestor = (Gestor) sistema.getUtilizadorligado();
        try {
            CentroVacinacao cv = sistema.getCentrosVacinacoes().getCentroVacinacaoPorGestor(gestor);
            String cod = cv.getCodigo();
            JanelaGerirVacinas j = new JanelaGerirVacinas(sistema, bd, cod);
            j.setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "O Gestor não tem nenhum Centro associado", "ERRO", HEIGHT);
        }

    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        Gestor gestor = (Gestor) sistema.getUtilizadorligado();
        try {
            CentroVacinacao cv = sistema.getCentrosVacinacoes().getCentroVacinacaoPorGestor(gestor);
            String cod = cv.getCodigo();
            JanelaListarUtentesAssociados j = new JanelaListarUtentesAssociados(sistema, bd, cod);
            j.setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "O Gestor não tem nenhum Centro associado", "ERRO", HEIGHT);
        }
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        Gestor gestor = (Gestor) sistema.getUtilizadorligado();
        try {
            CentroVacinacao cv = sistema.getCentrosVacinacoes().getCentroVacinacaoPorGestor(gestor);
            String cod = cv.getCodigo();
            JanelaUtentesParaVacinar j = new JanelaUtentesParaVacinar(sistema, bd, cod);
            j.setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "O Gestor não tem nenhum Centro associado", "ERRO", HEIGHT);
        }

    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        Gestor g = (Gestor) sistema.getUtilizadorligado();
        try {
            CentroVacinacao centro = sistema.getCentrosVacinacoes().getCentroVacinacaoPorGestor(g);
            JanelaFaltasUtentes j = new JanelaFaltasUtentes(sistema, bd, centro);
            j.setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "O Gestor não tem nenhum Centro associado", "ERRO", HEIGHT);
        }
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem16ActionPerformed
        Gestor g = (Gestor) sistema.getUtilizadorligado();
        try {
            CentroVacinacao centro = sistema.getCentrosVacinacoes().getCentroVacinacaoPorGestor(g);
            JanelaEstatisticaVacinacao j = new JanelaEstatisticaVacinacao(sistema, bd, centro);
            j.setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "O Gestor não tem nenhum Centro associado", "ERRO", HEIGHT);
        }
    }//GEN-LAST:event_jMenuItem16ActionPerformed

    private void jMenuItem17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem17ActionPerformed
        JanelaEstatisticaVacinacaoAdministrador j = new JanelaEstatisticaVacinacaoAdministrador(sistema, bd);
        j.setVisible(true);

    }//GEN-LAST:event_jMenuItem17ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Ladmin;
    private javax.swing.JLabel Lgestor;
    private javax.swing.JLabel Lutente;
    private javax.swing.JLabel UtiLigado;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenu menuAdmin;
    private javax.swing.JMenu menuGestor;
    private javax.swing.JMenu menuUtente;
    // End of variables declaration//GEN-END:variables

    /**
     *
     */
    private void preencherImagem() {
        if (sistema.getUtilizadorligado() instanceof Gestor) {
            Lgestor.setVisible(true);
        }
        if (sistema.getUtilizadorligado() instanceof Administrador) {
            Ladmin.setVisible(true);
        }
        if (sistema.getUtilizadorligado() instanceof Utente) {
            Lutente.setVisible(true);
        }
    }

    // Metodo para so ser possivel fazer a primeira marcação!! ou seja, se ele conseguir ir buscar uma data, quer dizer que ele tem data marcada, senão tem de a marcar
    /**
     *
     */
    private void menuUtente() {
        Utente u = (Utente) sistema.getUtilizadorligado();
        try {
            if (u.getCentrovacinacao().getAgendaMarcacoes().dataProximaMarcacao(u) == null) {
                jMenuItem12.setVisible(true);
            } else {
                jMenuItem12.setVisible(false);
            }

        } catch (Exception e) {
            jMenuItem12.setVisible(true);
        }
    }
}
