/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FRONTEND;

import BACKEND.Sistema;
import BACKEND.Utente;

/**
 *
 * @author guilh
 */
public class JanelaConsultarCentroDeVacinacao extends javax.swing.JFrame {

    /**
     *
     */
    private Sistema sistema;

    /**
     *
     */
    private Utente utente;

    /**
     *
     */
    private Serializacao.Serializacao bd;

    /**
     *
     * @param sistema
     * @param utente
     * @param bd
     */
    public JanelaConsultarCentroDeVacinacao(Sistema sistema, Utente utente, Serializacao.Serializacao bd) {
        initComponents();
        this.sistema = sistema;
        this.utente = utente;
        this.bd = bd;
        this.setTitle("Centro de Vacinação do Utente");
        this.setResizable(false);
        Lcodigo.setText(utente.getCentrovacinacao().getCodigo());
        Lloccalidade1.setText(utente.getCentrovacinacao().getLocalidade());
        Lmorada.setText(utente.getCentrovacinacao().getMorada());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Lcodigo = new javax.swing.JLabel();
        Lmorada = new javax.swing.JLabel();
        Lloccalidade1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Centro de Vacinação");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 12, 154, 28));

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Código:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 60, 75, -1));

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Localidade:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 102, 75, -1));

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Morada");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 148, 75, -1));

        Lcodigo.setForeground(new java.awt.Color(0, 0, 0));
        Lcodigo.setText("jLabel6");
        getContentPane().add(Lcodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 60, 168, -1));

        Lmorada.setForeground(new java.awt.Color(0, 0, 0));
        Lmorada.setText("jLabel6");
        getContentPane().add(Lmorada, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 148, 142, -1));

        Lloccalidade1.setForeground(new java.awt.Color(0, 0, 0));
        Lloccalidade1.setText("jLabel6");
        getContentPane().add(Lloccalidade1, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 102, 157, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons/Consultar Centro Vacinacao.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 270));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Lcodigo;
    private javax.swing.JLabel Lloccalidade1;
    private javax.swing.JLabel Lmorada;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables

}
