/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FRONTEND;

import BACKEND.Gestor;
import BACKEND.Sistema;
import javax.swing.JOptionPane;

/**
 *
 * @author guilh
 */
public class JanelaEditarGestor extends javax.swing.JFrame {

    /**
     *
     */
    private Sistema sistema;

    /**
     *
     */
    private Serializacao.Serializacao bd;

    /**
     *
     */
    private String username;

    /**
     *
     * @param sistema
     * @param username
     * @param bd
     */
    public JanelaEditarGestor(Sistema sistema, String username, Serializacao.Serializacao bd) {
        initComponents();

        this.sistema = sistema;
        this.username = username;
        this.bd = bd;
        this.setTitle("Editar Gestor");
        this.setResizable(false);
        preencherDados();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Lemail = new javax.swing.JTextField();
        Lpassword = new javax.swing.JTextField();
        Lnome = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        Jluser = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jButton2.setText("Editar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Username");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 94, 34));

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Email");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 94, 34));

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Password");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 94, 34));

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Nome");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 94, 34));

        Lemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LemailActionPerformed(evt);
            }
        });
        getContentPane().add(Lemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 120, -1));

        Lpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LpasswordActionPerformed(evt);
            }
        });
        getContentPane().add(Lpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, 120, -1));

        Lnome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LnomeActionPerformed(evt);
            }
        });
        getContentPane().add(Lnome, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 120, -1));

        jButton3.setText("Confirmar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, 104, 37));

        jButton1.setText("Voltar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 350, 104, 37));
        getContentPane().add(Jluser, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 47, 111, -1));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 120, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons/Editar Gestor.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-6, -5, 410, 420));

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LemailActionPerformed

    private void LpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LpasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LpasswordActionPerformed

    private void LnomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LnomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LnomeActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed


    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        if (Lnome.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Introduza a sua localidade", "Dados em falta", JOptionPane.WARNING_MESSAGE);
            Lnome.requestFocus();
            return;
        }
        if (Lemail.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Introduza a sua morada", "Dados em falta", JOptionPane.WARNING_MESSAGE);
            Lemail.requestFocus();
            return;
        }
        if (Lpassword.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Introduza o número de postos", "Dados em falta", JOptionPane.WARNING_MESSAGE);
            Lpassword.requestFocus();
            return;
        }

        String nome = Lnome.getText();
        String email = Lemail.getText();
        String password = Lpassword.getText();

        Gestor g = (Gestor) sistema.getUtilizadores().getGestor(username);
        g.setNome(nome);
        g.setEmail(email);
        g.setPassword(password);

        JanelaListarGestores j = new JanelaListarGestores(sistema, bd);
        j.setVisible(true);
        dispose();

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JanelaListarGestores j = new JanelaListarGestores(sistema, bd);
        j.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Jluser;
    private javax.swing.JTextField Lemail;
    private javax.swing.JTextField Lnome;
    private javax.swing.JTextField Lpassword;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables

    /**
     *
     */
    private void preencherDados() {
        Gestor g = (Gestor) sistema.getUtilizadores().getGestor(username);

        jLabel2.setText(username);
        Lnome.setText(g.getNome());
        Lemail.setText(g.getEmail());
        Lpassword.setText(g.getPassword());

    }
}
