/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FRONTEND;

import BACKEND.CentroVacinacao;
import BACKEND.Sistema;
import BACKEND.Vacina;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author guilh
 */
public class JanelaGerirVacinas extends javax.swing.JFrame {

    /**
     *
     */
    private Sistema sistema;

    /**
     *
     */
    private CentroVacinacao centro;

    /**
     *
     */
    private Serializacao.Serializacao bd;

    /**
     *
     * @param sistema
     * @param bd
     * @param cod
     */
    public JanelaGerirVacinas(Sistema sistema, Serializacao.Serializacao bd, String cod) {
        initComponents();
        this.sistema = sistema;
        this.bd = bd;
        this.setResizable(false);
        this.centro = sistema.getCentrosVacinacoes().CentroVacinacaoPorCod(cod);
        preencherTabela();
        this.setTitle("Vacinas");
        jLabel1.setText("Centro de Vacinação: " + cod);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Badicionar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Fabricante", "Vacinas"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 112, 494, 343));

        Badicionar.setText("Adicionar Vacinas");
        Badicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BadicionarActionPerformed(evt);
            }
        });
        getContentPane().add(Badicionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 140, 94));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 30, 337, 54));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons/Janela Gerir Vacinas.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BadicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BadicionarActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        int col = 0;
        int row = jTable1.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Selecione uma Vacina!");
            return;
        }

        String fabricante = (String) model.getValueAt(row, col);
        JanelaAdicionarVacinas j = new JanelaAdicionarVacinas(sistema, bd, fabricante, this.centro);
        j.setVisible(true);
        dispose();
    }//GEN-LAST:event_BadicionarActionPerformed

    /**
     *
     */
    private void preencherTabela() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        for (Vacina v : sistema.getVacinas().getListavacinas()) {
            String fabricante = v.getFabricante();
            long quantidade = centro.getStockvacinas().stockDisponivel(v);

            model.addRow(new Object[]{fabricante, quantidade});
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Badicionar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
