/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FRONTEND;

import BACKEND.Gestor;
import BACKEND.RepositorioUtilizador.UtilizadorDuplicadoException;
import BACKEND.Sistema;
import javax.swing.JOptionPane;

/**
 *
 * @author guilh
 */
public class JanelaAdicionarGestor extends javax.swing.JFrame {

    /**
     *
     */
    private Sistema sistema;

    /**
     *
     */
    private Serializacao.Serializacao bd;

    /**
     *
     * @param sistema
     * @param bd
     */
    public JanelaAdicionarGestor(Sistema sistema, Serializacao.Serializacao bd) {
        initComponents();
        this.sistema = sistema;
        this.bd = bd;
        this.setResizable(false);
        this.setTitle("Adicionar Gestor");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Lusername = new javax.swing.JTextField();
        Lemail = new javax.swing.JTextField();
        Lpass = new javax.swing.JTextField();
        Lnome = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jButton1.setText("Voltar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Nome");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 94, 34));

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Email");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 94, 34));

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Password");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 94, 34));

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Username:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 70, 34));

        Lusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LusernameActionPerformed(evt);
            }
        });
        getContentPane().add(Lusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 100, -1));

        Lemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LemailActionPerformed(evt);
            }
        });
        getContentPane().add(Lemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 100, -1));

        Lpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LpassActionPerformed(evt);
            }
        });
        getContentPane().add(Lpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 100, -1));

        Lnome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LnomeActionPerformed(evt);
            }
        });
        getContentPane().add(Lnome, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 100, -1));

        jButton3.setText("Criar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, 104, 37));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons/Adicionar Gestor1.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LusernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LusernameActionPerformed

    private void LemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LemailActionPerformed

    private void LpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LpassActionPerformed

    private void LnomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LnomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LnomeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        JanelaListarCentroVacinacoes j = new JanelaListarCentroVacinacoes(sistema, bd);
        j.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (Lusername.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Introduza o username", "Dados em falta", JOptionPane.WARNING_MESSAGE);
            Lusername.requestFocus();
            return;
        }
        if (Lnome.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Introduza o nome do gestor", "Dados em falta", JOptionPane.WARNING_MESSAGE);
            Lnome.requestFocus();
            return;
        }
        if (Lemail.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Introduza o email", "Dados em falta", JOptionPane.WARNING_MESSAGE);
            Lemail.requestFocus();
            return;
        }
        if (Lpass.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Introduza a password", "Dados em falta", JOptionPane.WARNING_MESSAGE);
            Lpass.requestFocus();
            return;
        }

        String username = Lusername.getText();
        String nome = Lnome.getText();
        String email = Lemail.getText();
        String password = Lpass.getText();

        try {
            sistema.getUtilizadores().adicionarUtilizadorUsername(new Gestor(username, password, email, nome));
            dispose();
            JanelaListarGestores j = new JanelaListarGestores(sistema, bd);
            j.setVisible(true);

        } catch (UtilizadorDuplicadoException ex) {
            JOptionPane.showMessageDialog(this, "Username já utilizado!");
            Lusername.requestFocus();
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Lemail;
    private javax.swing.JTextField Lnome;
    private javax.swing.JTextField Lpass;
    private javax.swing.JTextField Lusername;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
