/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FRONTEND;

import BACKEND.Sistema;
import javax.swing.JOptionPane;

/**
 *
 * @author guilh
 */
public class JanelaLogin extends javax.swing.JFrame {

    /**
     *
     */
    private Sistema sistema;

    /**
     *
     */
    private Serializacao.Serializacao bd;

    /**
     *
     * @param sistema
     * @param bd
     */
    public JanelaLogin(Sistema sistema, Serializacao.Serializacao bd) {
        initComponents();

        //Não permite o redimensionamento da janela
        this.setResizable(false);

        //Mostra a centralização da janela
        this.setLocationRelativeTo(null);

        //O processo de fecho da janela será controlado pelo programa
        this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        this.setTitle("Janela Login");

        this.sistema = sistema;
        this.bd = bd;

        txtUtilizador.requestFocus();
    }

    /**
     *
     */
    private void autenticar() {
        if (txtUtilizador.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Introduza um username!", "UTILIZADOR EM FALTA", JOptionPane.WARNING_MESSAGE);
            txtUtilizador.requestFocus();
            return;
        }

        if (txtPassword.getPassword().length == 0) {
            JOptionPane.showMessageDialog(this, "Introduza a sua password!");
            txtPassword.requestFocus();
            return;
        }

        if (!sistema.autenticarUtilizador(txtUtilizador.getText(), new String(txtPassword.getPassword()))) {
            JOptionPane.showMessageDialog(this, "As credenciais introduzidas não correspondem a um utilizador válido.",
                    "Autenticação", JOptionPane.WARNING_MESSAGE);
            txtUtilizador.requestFocus();
        } else {
            //Devolve o controlo da aplicação para o método main
            dispose();
            JOptionPane.showMessageDialog(this, "Bem-vindo " + sistema.getUtilizadorligado().getUsername() + "!");
            JanelaPrincipal jp = new JanelaPrincipal(sistema, bd);
            jp.setVisible(true);

        }
    }

    /**
     *
     */
    private void registarUtente() {
        JanelaRegistarUtente psw = new JanelaRegistarUtente(sistema, null, sistema.getUtilizadores());
        //psw.setSize(545, 478);
        psw.setVisible(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        txtUtilizador = new javax.swing.JTextField();
        Bautenticar = new javax.swing.JButton();
        Bregistar = new javax.swing.JButton();
        Bterminar = new javax.swing.JButton();
        ola = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(txtUtilizador, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, 172, 26));

        Bautenticar.setText("Autenticar");
        Bautenticar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BautenticarActionPerformed(evt);
            }
        });
        getContentPane().add(Bautenticar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 330, 100, 30));

        Bregistar.setText("Registar");
        Bregistar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BregistarActionPerformed(evt);
            }
        });
        getContentPane().add(Bregistar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 330, 103, 30));

        Bterminar.setText("Terminar");
        Bterminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BterminarActionPerformed(evt);
            }
        });
        getContentPane().add(Bterminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 330, 100, 30));

        ola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                olaActionPerformed(evt);
            }
        });
        getContentPane().add(ola, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 260, -1, -1));

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Ver password");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 260, 155, 20));

        jLabel4.setFont(new java.awt.Font("Cambria", 1, 22)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Username");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 110, -1));

        jLabel3.setFont(new java.awt.Font("Cambria", 1, 22)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Palavra-passe");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 150, -1));

        jLabel2.setFont(new java.awt.Font("Microsoft Tai Le", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("App Covid-19");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, 180, 60));
        getContentPane().add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, 172, 26));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons/login.png"))); // NOI18N
        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BautenticarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BautenticarActionPerformed
        autenticar();
    }//GEN-LAST:event_BautenticarActionPerformed

    private void BregistarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BregistarActionPerformed

        registarUtente();
    }//GEN-LAST:event_BregistarActionPerformed

    private void BterminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BterminarActionPerformed
        sistema.terminar();
    }//GEN-LAST:event_BterminarActionPerformed

    private void olaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_olaActionPerformed
        if (ola.isSelected()) {
            txtPassword.setEchoChar((char) 0);
        } else {
            txtPassword.setEchoChar('*');
        }
    }//GEN-LAST:event_olaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bautenticar;
    private javax.swing.JButton Bregistar;
    private javax.swing.JButton Bterminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JCheckBox ola;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUtilizador;
    // End of variables declaration//GEN-END:variables
}
