/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FRONTEND;

import BACKEND.CentroVacinacao;
import BACKEND.Gestor;
import BACKEND.Sistema;
import BACKEND.Utilizador;
import javax.swing.JOptionPane;

/**
 *
 * @author guilh
 */
public class JanelaEditarCentroVacinacao extends javax.swing.JFrame {

    /**
     *
     */
    private Sistema sistema;

    /**
     *
     */
    private String cod;

    /**
     *
     */
    private Serializacao.Serializacao bd;

    /**
     *
     * @param sistema
     * @param cod
     * @param bd
     */
    public JanelaEditarCentroVacinacao(Sistema sistema, String cod, Serializacao.Serializacao bd) {
        initComponents();
        this.sistema = sistema;
        this.cod = cod;
        this.bd = bd;
        this.setTitle("Editar Centro Vacinação");
        this.setResizable(false);
        preencherDados();
        preencherGestores();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Lcod = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Llocalidade = new javax.swing.JTextField();
        Lmorada = new javax.swing.JTextField();
        Lpostos = new javax.swing.JTextField();
        Llimite = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        Lgestor = new javax.swing.JComboBox<>();
        jCod = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        Lcod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LcodActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Codigo:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 60, 100, 34));

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Localidade:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 107, 100, 40));

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Morada:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 160, 100, 40));

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Gestor:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 218, 100, 50));

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Numero de Postos:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 270, 110, 60));

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Limite Vacinações:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 340, 110, 40));
        getContentPane().add(Llocalidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 120, -1));
        getContentPane().add(Lmorada, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 120, -1));
        getContentPane().add(Lpostos, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, 120, -1));
        getContentPane().add(Llimite, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 350, 120, -1));

        jButton2.setText("Confirmar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 410, 104, 37));

        Lgestor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LgestorActionPerformed(evt);
            }
        });
        getContentPane().add(Lgestor, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 120, -1));
        getContentPane().add(jCod, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 60, 72, 40));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons/editar centro vacinação.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LcodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LcodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LcodActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        if (Llocalidade.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Introduza a sua localidade", "Dados em falta", JOptionPane.WARNING_MESSAGE);
            Llocalidade.requestFocus();
            return;
        }
        if (Lmorada.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Introduza a sua morada", "Dados em falta", JOptionPane.WARNING_MESSAGE);
            Lmorada.requestFocus();
            return;
        }
        if (Lpostos.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Introduza o número de postos", "Dados em falta", JOptionPane.WARNING_MESSAGE);
            Lpostos.requestFocus();
            return;
        }

        if (Llimite.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Introduza o limite máximo de vacinações", "Dados em falta", JOptionPane.WARNING_MESSAGE);
            Llimite.requestFocus();
            return;
        }
        String codigo = Lcod.getText();
        String localidade = Llocalidade.getText();
        String morada = Lmorada.getText();
        int postos = Integer.parseInt(Lpostos.getText());
        String cod_gestor = Lgestor.getItemAt(Lgestor.getSelectedIndex());
        int limite = Integer.parseInt(Llimite.getText());

        CentroVacinacao centro = sistema.getCentrosVacinacoes().CentroVacinacaoPorCod(cod);
        centro.setGestor((Gestor) sistema.getUtilizadores().getGestor(cod_gestor));
        centro.setLocalidade(localidade);
        centro.setMorada(morada);
        centro.setNumeroPostosAtendimento(postos);
        centro.setNumeroMaximoVacinacaoPorDia(limite);

        dispose();
        JanelaListarCentroVacinacoes j = new JanelaListarCentroVacinacoes(sistema, bd);
        j.setVisible(true);


    }//GEN-LAST:event_jButton2ActionPerformed

    private void LgestorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LgestorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LgestorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Lcod;
    private javax.swing.JComboBox<String> Lgestor;
    private javax.swing.JTextField Llimite;
    private javax.swing.JTextField Llocalidade;
    private javax.swing.JTextField Lmorada;
    private javax.swing.JTextField Lpostos;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jCod;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables

    /**
     *
     */
    private void preencherDados() {
        CentroVacinacao centro = sistema.getCentrosVacinacoes().CentroVacinacaoPorCod(cod);

        String localidade = centro.getLocalidade();
        String morada = centro.getMorada();
        int postos = centro.getNumeroPostosAtendimento();
        String cod_gestor = centro.getGestor().getUsername();
        int limite = centro.getNumeroMaximoVacinacaoPorDia();

        jCod.setText(cod);
        Llocalidade.setText(localidade);
        Lmorada.setText(localidade);
        // Lgestor //FALTA POR O GESTOR
        Llimite.setText(Integer.toString(limite));
        Lpostos.setText(Integer.toString(postos));

    }

    /**
     *
     */
    private void preencherGestores() {
        CentroVacinacao centro = sistema.getCentrosVacinacoes().CentroVacinacaoPorCod(cod);
        Gestor g = centro.getGestor();
        Lgestor.addItem(g.getUsername());
        for (Utilizador u : sistema.getUtilizadores().getListaUtilizador()) {
            if (u instanceof Gestor) {
                Gestor gestor = (Gestor) u;
                if (sistema.getCentrosVacinacoes().getCentroVacinacaoPorGestor(gestor) == null) {
                    Lgestor.addItem(u.getUsername());
                }
            }

        }

    }

}
