/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FRONTEND;

import BACKEND.RepositorioDatasAdministracao;
import BACKEND.RepositorioDoencas;
import BACKEND.RepositorioUtilizador;
import BACKEND.RepositorioUtilizador.UtilizadorDuplicadoException;
import BACKEND.Sistema;
import BACKEND.Utente;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author guilh
 */
public class JanelaRegistarUtente extends javax.swing.JFrame {

    /**
     *
     */
    private Sistema sistema;

    /**
     *
     */
    private Utente utente;

    /**
     *
     */
    private RepositorioUtilizador repositorio;

    /**
     *
     */
    private Serializacao.Serializacao bd;

    /**
     *
     * @param sistema
     * @param utente
     * @param repositorio
     */
    public JanelaRegistarUtente(Sistema sistema, Utente utente, RepositorioUtilizador repositorio) {
        initComponents();
        //Não permite o redimensionamento da janela
        this.setResizable(false);

        //Mostra a centralização da janela
        this.setLocationRelativeTo(null);

        //O processo de fecho da janela será controlado pelo programa
        this.setTitle("Registar novo Utente");

        this.sistema = sistema;
        this.utente = utente;

        //Guarda a referencia ao repositorio;
        this.repositorio = repositorio;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        numeroSNS = new javax.swing.JLabel();
        Nome = new javax.swing.JLabel();
        localidade = new javax.swing.JTextField();
        registarUtente = new javax.swing.JButton();
        label2 = new javax.swing.JLabel();
        label = new javax.swing.JLabel();
        label8 = new javax.swing.JLabel();
        label3 = new javax.swing.JLabel();
        label4 = new javax.swing.JLabel();
        label7 = new javax.swing.JLabel();
        nome1 = new javax.swing.JTextField();
        morada1 = new javax.swing.JTextField();
        telemovel = new javax.swing.JTextField();
        username = new javax.swing.JTextField();
        password = new javax.swing.JTextField();
        email1 = new javax.swing.JTextField();
        dataNascimento1 = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        numeroSNS.setForeground(new java.awt.Color(0, 0, 0));
        numeroSNS.setText("NºSNS");
        getContentPane().add(numeroSNS, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 22, 73, 24));

        Nome.setForeground(new java.awt.Color(0, 0, 0));
        Nome.setText("Nome");
        getContentPane().add(Nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 52, 24));
        getContentPane().add(localidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 121, 128, -1));

        registarUtente.setText("Registar");
        registarUtente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registarUtenteActionPerformed(evt);
            }
        });
        getContentPane().add(registarUtente, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 390, 98, -1));

        label2.setForeground(new java.awt.Color(0, 0, 0));
        label2.setText("Localidade");
        getContentPane().add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 84, 24));

        label.setForeground(new java.awt.Color(0, 0, 0));
        label.setText("Morada");
        getContentPane().add(label, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 52, 24));

        label8.setForeground(new java.awt.Color(0, 0, 0));
        label8.setText("Password");
        getContentPane().add(label8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 84, 24));

        label3.setForeground(new java.awt.Color(0, 0, 0));
        label3.setText("Telemóvel");
        getContentPane().add(label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 84, 24));

        label4.setForeground(new java.awt.Color(0, 0, 0));
        label4.setText("Data Nascimento");
        getContentPane().add(label4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 98, 24));

        label7.setForeground(new java.awt.Color(0, 0, 0));
        label7.setText("Email");
        getContentPane().add(label7, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 254, 70, 30));
        getContentPane().add(nome1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 63, 128, -1));
        getContentPane().add(morada1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 91, 128, -1));
        getContentPane().add(telemovel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 128, -1));
        getContentPane().add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 25, 128, -1));
        getContentPane().add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, 128, -1));
        getContentPane().add(email1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 180, -1));
        getContentPane().add(dataNascimento1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 130, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons/Janela Registrar Utente.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registarUtenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registarUtenteActionPerformed

        if (nome1.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Introduza o seu nome", "Dados em falta", JOptionPane.WARNING_MESSAGE);
            localidade.requestFocus();
            return;
        }
        if (morada1.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Introduza a sua morada", "Dados em falta", JOptionPane.WARNING_MESSAGE);
            morada1.requestFocus();
            return;
        }
        if (localidade.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Introduza a sua localidade", "Dados em falta", JOptionPane.WARNING_MESSAGE);
            localidade.requestFocus();
            return;
        }
        if (telemovel.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Introduza o seu telemovel", "Dados em falta", JOptionPane.WARNING_MESSAGE);
            telemovel.requestFocus();
            return;
        }
        if (dataNascimento1.getDate() == null) {
            JOptionPane.showMessageDialog(this, "Introduza a sua data de Nascimento", "Dados em falta", JOptionPane.WARNING_MESSAGE);
            dataNascimento1.requestFocus();
            return;
        } else {
            Date input = dataNascimento1.getDate();
            LocalDate dataNascimento = input.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
            if (dataNascimento.isAfter(LocalDate.now())) {
                JOptionPane.showMessageDialog(this, "Data introduzida inválida!");
                dataNascimento1.requestFocus();
                return;
            }

        }

        if (username.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Introduza o username", "Dados em falta", JOptionPane.WARNING_MESSAGE);
            username.requestFocus();
            if (sistema.getUtilizadores().existeUtilizador(username.getText())) {
                JOptionPane.showMessageDialog(this, "Username já utilizado, tente novamente", "ERRO! Dados já utilizados", JOptionPane.WARNING_MESSAGE);
                username.setText("");
                username.requestFocus();
                return;
            }
        }
        if (email1.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Introduza o email", "Dados em falta", JOptionPane.WARNING_MESSAGE);
            email1.requestFocus();
            if (sistema.getUtilizadores().verificarEmail(email1.getText())) {
                JOptionPane.showMessageDialog(this, "Email já utilizado, tente novamente", "ERRO! Dados já utilizados", JOptionPane.WARNING_MESSAGE);
                email1.setText("");
                email1.requestFocus();
                return;
            }
        }
        if (password.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Introduza a password", "Dados em falta", JOptionPane.WARNING_MESSAGE);
            password.requestFocus();
            return;
        }

        String nome = nome1.getText();
        String morada = morada1.getText();
        String localidad = localidade.getText();
        String tele = telemovel.getText();
        Date data = dataNascimento1.getDate();
        LocalDate dataNadcimento = data.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        String user = username.getText();
        String email = email1.getText();
        String pass = password.getText();

        try {
            sistema.getUtilizadores().adicionarUtilizadorUsername(new Utente(user, morada, localidad, dataNadcimento, tele, new RepositorioDoencas(), null, null, new RepositorioDatasAdministracao(), user, pass, email, nome));
            dispose();
        } catch (UtilizadorDuplicadoException ex) {
            JOptionPane.showMessageDialog(this, "Numero de SNS já utilizado!");
            username.requestFocus();

        }


    }//GEN-LAST:event_registarUtenteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Nome;
    private com.toedter.calendar.JDateChooser dataNascimento1;
    private javax.swing.JTextField email1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel label;
    private javax.swing.JLabel label2;
    private javax.swing.JLabel label3;
    private javax.swing.JLabel label4;
    private javax.swing.JLabel label7;
    private javax.swing.JLabel label8;
    private javax.swing.JTextField localidade;
    private javax.swing.JTextField morada1;
    private javax.swing.JTextField nome1;
    private javax.swing.JLabel numeroSNS;
    private javax.swing.JTextField password;
    private javax.swing.JButton registarUtente;
    private javax.swing.JTextField telemovel;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
